name: Linting & Testing

on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
  push:
    branches:
      - main
      - feature/*

jobs:
  lint-and-test:
    name: Lint and Test Code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r dev_requirements.txt
          pip install -r requirements.txt

      - name: Lint with flake8
        run: |
          flake8 . --count --show-source --statistics

      - name: Lint with yamllint
        run: |
          yamllint -c .yamllint.yml .

      - name: Run PyTest Unit Tests
        run: |
          pytest tests/unit_tests.py --doctest-modules \
          --junitxml=junit/test-results.xml \
          --cov=com --cov-report=xml --cov-report=html

      - name: Build coverage file
        run: |
          pytest --cache-clear --cov=app tests/ > pytest-coverage.txt

      - name: pytest-coverage-commentator
        uses: coroo/pytest-coverage-commentator@v1.0.2
        with:
          pytest-coverage: pytest-coverage.txt
